CONFIG_ARTINCHIP_D13X_BOOT_CONTRACT=y
CONFIG_KERNEL_ENTRY="aic_handoff_entry"
CONFIG_PRINTK=y
CONFIG_MINIMAL_LIBC=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_BOOT_BANNER=n
CONFIG_GPIO=n
CONFIG_DMA=n
CONFIG_NETWORKING=n
CONFIG_FILE_SYSTEM=n
CONFIG_DISPLAY=n
CONFIG_CAN=n
